on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master, develop]

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Nextshot
        run: make
      - name: Run Shellcheck
        uses: ludeeus/action-shellcheck@master
